### ISSUE TITLE
Publikovanie opatrení: Checklist

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-help/korona-gov#22]
**Checklist pred nasadenim na www.opatrenia.korona.gov.sk:**

- [x] Dokončiť preklopenie z Figmy do HTML na adrese: https://wpkorona.lamer.sk
- [x] Skontrolovať všetky linky, či sa viem správne dostať vždy tam, kam máme (Ideálne by bolo scenár 1, skontrolovaný kým, scenár 2 skotrolovaný kým)
- [x]  Opraviť, ak sa nachádzajú v HTML chyby, pretože s ním robili ľudia, ktorí to videli včera a dnes prvýkrat ale aj layout (napr. https://github.com/slovensko-help/korona-gov/issues/15)
- [x] Nahodit cookie consent, GA tracking (https://github.com/slovensko-help/korona-gov/issues/47)
- [x] Vyhodit nase flagy z nadpisov clankov (https://github.com/slovensko-help/korona-gov/issues/55)
- [x] Skontrolovat, ci su spravne nastavene defaulty pre zbalene/rozbalene accordiony (v inkognito mode, kedze browser si pamata stav zbaleny/rozbaleny) (https://github.com/slovensko-help/korona-gov/issues/52)
- [x] Doladit homepage (https://github.com/slovensko-help/korona-gov/issues/57)
- [x]  Doladiť SEO, metatagy, *titles*….
- [x]  Poslať na finálnu kontrolu ministerstvu
- [x] Nastavit monitoring na vsetky dolezite linky (hlavne tlaciva) (https://github.com/slovensko-help/korona-gov/issues/54)
- [x]  Získať schválenie obsahu ministerstvom
- [x] Kontrola prístupnosti (https://github.com/slovensko-help/korona-gov/issues/7)
- [x] Aktualizovať statiku na https://korona.slovensko.help/
- [x] Preklikať a skontrolovať aktualizovanú statiku (https://github.com/slovensko-help/korona-gov/issues/74)
- [x] Doplnit vyhlasenie o pristupnosti
- [x] Informovať Úradné tlačové oddelenie (https://github.com/slovensko-help/korona-gov/issues/8)

**Checklist po nasadeni na www.opatrenia.korona.gov.sk:**

- [x] Otestovat, ze cookie conset bar nezobrazi druhykrat po jeho odkliknuti (vid detaily tu: https://github.com/slovensko-help/korona-gov/issues/73)

**Comment by filiplikavcan** [comment]
Oznacte vo WP clanky, ktore su cele preklopene do HTML [WIP:autor | CHECK]

**Comment by athelas64** [comment]
prosím do checklistu doplniť bod, ktorý vyplýva z legislatívy - vytvoriť a zverejniť vyhlásenie o prístupnosti (voľne to naväzuje na kontrolu prístupnosti)

**Comment by filiplikavcan** [comment]
@athelas64 Vyhlasenie o pristupnosti je v akom stave, pls?

**Comment by athelas64** [comment]
je pripravené na publikovanie, niektoré issues v ňom spomínané je ale podľa mňa v silách tímu vyriešiť, tak tie, ktoré ešte nie sú ako issues by som sem doplnil
